#include<stdio.h>
#include<stdlib.h>
#include<unistd.h>
#include<string.h>
#include<sys/types.h>
#include<sys/socket.h>
#include<netinet/in.h>
#include<netdb.h>
#include<ctype.h>
#include<openssl/md5.h>


#define BUFFER_SIZE 512
#define FILENAME "rec.txt"

void error(const char *msg){
	perror(msg);
	exit(0);
}


int main(int argc, char *argv[]){

	int sockfd, portno;
	struct sockaddr_in serv_addr;
	struct hostent *server;
	char buffer[BUFFER_SIZE];
	char ack_md5[BUFFER_SIZE];

	if(argc < 3){
		printf("\n !! Usage:: filename host addresss port number ! Client terminated...");
		exit(0);
	}
	
	portno = atoi(argv[2]);
	// Socket Creation...
	sockfd = socket(AF_INET, SOCK_STREAM, 0);

	if(sockfd < 0){
		error("Error In Opening Socket..!!!");
	}

	server = gethostbyname(argv[1]);

	if(server == NULL){
		fprintf(stderr, "error, no host found");
		exit(0);
	}
	
	//cleaning 
	bzero((char *)&serv_addr, sizeof(serv_addr));

	//attributes	
	serv_addr.sin_family = AF_INET;
	bcopy((char *)server -> h_addr, (char *)&serv_addr.sin_addr.s_addr, server -> h_length);

	serv_addr.sin_port = htons(portno);

	if(connect(sockfd,(struct sockaddr *) &serv_addr, sizeof(serv_addr)) < 0){
		error("Error in Connecting Socket !!");
		bzero(buffer,BUFFER_SIZE);
	}

	FILE *f, *tf;
	int words = 0;
	char cha;
	int buffsize;
	size_t newlen;
	char num[BUFFER_SIZE];
	char *ack;
	memset(buffer, 0 , sizeof(buffer));
	//bzero((char *)&c, sizeof(c));
	
	//reading file size
	read(sockfd, &buffsize, sizeof(buffsize));
	
	//reading file from server
	f = fopen(FILENAME,"w+");
	int result = read(sockfd, buffer, sizeof(buffer));
		if(result > 0){
			printf(" len file :%d\n", buffsize);
			fwrite(buffer, sizeof(char), buffsize, f);
			//ch++;
			printf("%s", buffer);
			//fputs("\n",f);
			
		}
	fclose(f);
	// reading ack from server 
	read(sockfd, ack_md5, sizeof(ack_md5));
	
	FILE *ff = popen("md5sum rec.txt | cut -f 1 -d ' '", "r");
	if(ff != NULL){
		
		if(fgets(num, sizeof(num), ff))
			printf("%s",num);
		pclose(ff);
	}
	printf("\n md5 recieved from server: %s \n", ack_md5);
	printf("\n md5 generated by client: %s \n", num);
	
	if(strcmp(num,ack_md5) == 0){
		printf("\nFile Received Successfuly ..\n");
		ack = "Ack_Success";
		write(sockfd, ack, sizeof(ack));
	}
	else
		printf("\nFile Currupted\n");
	
	
	
	//write(sockfd, &buffsize, sizeof(int));
	//write(sockfd, buffer, sizeof(buffer));
	
	
	
	close(sockfd);
	return 0;


}

